[project]
name = "vibestunes"
version = "0.1.0"
description = "The modern iTunes alternative for syncing lossless FLACs from Plex to your Rockbox iPod"
authors = [
    { name = "orviwan" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyside6>=6.8.0",
    "plexapi>=4.16.0",
    "mutagen>=1.47.0",
    "requests>=2.31.0",
]

[project.scripts]
vibestunes = "vibestunes.main:main"
vibesTunes = "vibestunes.main:main"
vibetunes = "vibestunes.main:main"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
